---
all:
  children:
    actual_servers:
      hosts:
        server-9:
          ansible_host: 11.11.11.11
          ansible_user: root
          ansible_port: 22
          server_name: server-9
          status: prepared
          ansible_password: "{{ vault_ansible_password | default('CHANGE_ME') }}"
          server_domain: "{{ vault_server_domain | default('CHANGE_ME') }}"
          os_name: Ubuntu
          host_provider: H2.nexus
          location: new

  hosts:
    localhost:
      ansible_connection: local
