all:
  children:
    new_servers:
      hosts:
        new-server-1:
          ansible_host: 10.10.10.10
          ansible_user: root
          ansible_port: 22
          ansible_password: "{{ vault_ansible_password | default('CHANGE_ME') }}"
          server_domain: "{{ vault_server_domain | default('CHANGE_ME') }}"
          ansible_ssh_common_args: "-o PasswordAuthentication=yes -o PubkeyAuthentication=no"
          server_name: "new-server-1"
        new-server-2:
          ansible_host: 11.11.11.11
          ansible_user: root
          ansible_port: 22
          ansible_password: "{{ vault_ansible_password | default('CHANGE_ME') }}"
          server_domain: "{{ vault_server_domain | default('CHANGE_ME') }}"
          ansible_ssh_common_args: "-o PasswordAuthentication=yes -o PubkeyAuthentication=no"
          server_name: "new-server-1"

    old_servers:
      hosts:
        old-server-1:
          ansible_host: 12.12.12.12
          ansible_user: root
          ansible_port: 22
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          server_name: "old-server-1"
          server_domain: "{{ vault_server_domain | default('CHANGE_ME') }}"
        old-server-2:
          ansible_host: 91.218.246.209
          ansible_user: root
          ansible_port: 22
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          server_name: "old-server-1"
          server_domain: "domain.com"

  hosts:
    localhost:
      ansible_connection: local
