- name: Get Remnawave Node pubKey
  hosts: localhost
  gather_facts: false
  vars:
    remnawave_token: "{{ vault_remnawave_token | default('CHANGE_ME') }}"
    uuid: "$uuid"
  tasks:
    - name: Request pubKey from Remnawave API
      uri:
        url: "https://{{ remnawave_domain }}/api/keygen/{{ uuid }}"
        method: GET
        headers:
          Authorization: "Bearer {{ remnawave_token }}"
        return_content: yes
        status_code: 200
      register: remnawave_response

    - name: Save pubKey to file
      copy:
        dest: "./remnawave_pubkey.pem"
        content: "{{ remnawave_response.json.response.pubKey }}"
      when: remnawave_response.json.response.pubKey is defined
