- name: Создать новую ноду через RemnaWave API
  hosts: servers
  gather_facts: no
  vars:
    api_token: "{{ vault_remnawave_api_token | default('CHANGE_ME') }}"
    api_url: "https://{{ remnawave_domain }}/api/nodes"
  tasks:
    - name: Создать ноду через RemnaWave API
      uri:
        url: "{{ api_url }}"
        method: POST
        headers:
          Authorization: "Bearer {{ api_token }}"
          Content-Type: "application/json"
        body: |
          {
            "name": "{{ server_name }}",
            "address": "{{ ansible_host }}",
            "port": 2222,
            "isTrafficTrackingActive": false,
            "trafficLimitBytes": 0,
            "notifyPercent": 0,
            "trafficResetDay": 1,
            "countryCode": "{{ location }}",
            "consumptionMultiplier": 0.1,
            "configProfile": {
              "activeConfigProfileUuid": "$uuid",
              "activeInbounds": ["$inbound"]
            },
            "providerUuid": null
          }
        body_format: json
        return_content: yes
        status_code: 201
      register: create_node_response

    - name: Сохранить UUID новой ноды
      set_fact:
        new_node_uuid: "{{ create_node_response.json.response.uuid }}"

    - name: Пауза 20 секунд
      pause:
        seconds: 20

    - name: Получить список всех нод (свежий список с учётом новой)
      uri:
        url: "{{ api_url }}"
        method: GET
        headers:
          Authorization: "Bearer {{ api_token }}"
        return_content: yes
      register: node_status_response

    - name: Найти новую ноду по UUID
      set_fact:
        target_node: "{{ node_status_response.json.response
          | selectattr('uuid', 'equalto', new_node_uuid)
          | list
          | first }}"

    - name: Показать статус выбранной ноды
      debug:
        msg: |
          Имя: {{ target_node.name }}
          UUID: {{ target_node.uuid }}
          Онлайн: {{ target_node.isNodeOnline }}
          isConnected: {{ target_node.isConnected }}
          Последний статус: {{ target_node.lastStatusMessage }}
      when: target_node is defined and target_node is not none

    - name: Показать ответ API
      debug:
        var: create_node_result.content
