---
- name: REFERAL DB REPIC
  hosts: servers
  become: yes
  tasks:

    - name: Проверка наличия Docker на проде
      command: docker --version
      register: docker_check
      failed_when: docker_check.rc != 0

    - name: Проверка, что контейнер prod запущен
      shell: docker ps --filter "name={{ prod_container }}" --format '{{ "{{.Names}}" }}'
      register: prod_container_check
      failed_when: "'{{ prod_container }}' not in prod_container_check.stdout"

    - name: Копирование дампа с прода на dev
      fetch:
        src: "{{ dump_path }}"
        dest: "/tmp/prod_dump_{{ inventory_hostname }}.sql"
        flat: yes

    - name: Отправка дампа в dev-контейнер
      delegate_to: "{{ dev_host }}"
      become: yes
      vars:
        ansible_ssh_user: "{{ dev_user_ssh }}"
      copy:
        src: "/tmp/prod_dump_{{ inventory_hostname }}.sql"
        dest: "{{ dump_path }}"
        mode: '0644'

    - name: Полная очистка dev базы данных (удаление и пересоздание схемы)
      delegate_to: "{{ dev_host }}"
      become: yes
      vars:
        ansible_ssh_user: "{{ dev_user_ssh }}"
      shell: |
        docker exec -i {{ dev_container }} psql -U {{ dev_user }} -d template1 -c "DROP DATABASE IF EXISTS {{ dev_db }} WITH (FORCE);"
        docker exec -i {{ dev_container }} psql -U {{ dev_user }} -d template1 -c "CREATE DATABASE {{ dev_db }};"
      environment:
        PGPASSWORD: "{{ dev_pass }}"
      args:
        executable: /bin/bash
      register: cleanup_result
      failed_when: cleanup_result.rc != 0

    - name: Применение дампа в dev-контейнере
      delegate_to: "{{ dev_host }}"
      become: yes
      vars:
        ansible_ssh_user: "{{ dev_user_ssh }}"
      shell: |
        cat {{ dump_path }} | docker exec -i {{ dev_container }} psql -U {{ dev_user }} -d {{ dev_db }}
      environment:
        PGPASSWORD: "{{ dev_pass }}"
      args:
        executable: /bin/bash
      register: restore_result
      failed_when: restore_result.rc != 0

    - name: Очистка временного файла на контроллере
      local_action:
        module: file
        path: "/tmp/prod_dump_{{ inventory_hostname }}.sql"
        state: absent

    - name: Очистка дампа на dev
      delegate_to: "{{ dev_host }}"
      become: yes
      vars:
        ansible_ssh_user: "{{ dev_user_ssh }}"
      file:
        path: "{{ dump_path }}"
        state: absent

    - name: Проверка, что дамп успешно применился в dev
      delegate_to: "{{ dev_host }}"
      vars:
        ansible_ssh_user: "{{ dev_user_ssh }}"
      shell: docker exec -i {{ dev_container }} psql -U {{ dev_user }} -d {{ dev_db }} -c '\dt'
      register: check_dev
      failed_when: check_dev.rc != 0
